default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: laplandija
  username: postgres
  password: postgres

staging:
  <<: *default
  database: laplandija
  username: laplandija
  password: laplandija

production:
  <<: *default
  database: laplandija
  username: laplandija
  password: efb3bd5daa91cb5809d799c4309e134edatabase.yml